### ISSUE TITLE
get_posts places `community_id` in the headers when it should be a parameter

### ISSUE THREAD

**Issue by ajstamps** [LemmyWorld/plemmy#10]
God I hope I didn't accidentally dump my creds.

In case I'm using it wrong, here is the code with the important bits changed:

```
from plemmy import LemmyHttp

community_id = 60412  # this is just a test community
srv = LemmyHttp("https://lemmy.world")

srv.login("<username>", "<password>")
posts = srv.get_posts(community_id=community_id)

print(posts.json())
```

currently (from what I can tell) it just grabs the latest posts from the Lemmy instance. 

[Link to community for your convenience](https://lemmy.world/c/lemmyholotest)

Postman tests:
Param:
![image](https://github.com/tjkessler/plemmy/assets/13308215/5ff5efeb-40df-49a1-8a1f-40e72bc33680)

Header:
![image](https://github.com/tjkessler/plemmy/assets/13308215/e7a8cd5c-169f-460e-a43c-8614f5c6f70e)

**Comment by tjkessler** [comment]
Hi @ajstamps,

Nice find, should be fixed as of https://github.com/tjkessler/plemmy/pull/11, newest version will be 0.2.6! I believe this issue is similar to the one found in https://github.com/tjkessler/plemmy/pull/3. 

Let me know if you're still having trouble and we'll re-open the issue!

Travis

**Comment by ajstamps** [comment]
Ah, missed that. My bad, thanks for the quick updates!
